/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.Journalist;

import business.dbArticle;
import business.dbJournalist;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.Journalist;
import ui.Main.LoginJFrame;

/**
 *
 * @author Azadeh
 */
public class JournalistMain extends javax.swing.JFrame {

    private final Journalist journalist;
    private final dbArticle articles;

    /**
     * Creates new form JournalistMain
     *
     * @param JID
     */
    public JournalistMain(int JID) {

        initComponents();

        articles = new dbArticle();
        this.journalist = new dbJournalist().Find(JID);
        lblWelcome.setText("Welcome " + journalist.getFirstName() + " " + journalist.getLastName());

        PapulateArticleTable();
    }

    private void PapulateArticleTable() {

        DefaultTableModel model = (DefaultTableModel) tblArticles.getModel();
        model.setRowCount(0);

        for (var item : articles.GetArticlesOfJournalist(this.journalist.getId())) {

            Object[] row = new Object[7];
            row[0] = item.getId();
            row[1] = item.getRegisterTime();
            row[2] = item.getTitle();
            row[3] = (item.getApproval() != null ? item.getApproval().getFirstName() + " " + item.getApproval().getLastName() : "Unknown");
            row[4] = item.getStatus();
            row[5] = item.getComment();
            row[6] = item.getLastEditTime();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblArticles = new javax.swing.JTable();
        btnAddArticle = new javax.swing.JButton();
        btnEditArticle = new javax.swing.JButton();
        btnDeleteArticle = new javax.swing.JButton();
        lblSearchArticle = new javax.swing.JLabel();
        txtSearchArticle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Journalits Main Menu...");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TitlePanel.setBackground(new java.awt.Color(204, 0, 102));
        TitlePanel.setForeground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(0, 102, 102));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Journalits Main Menu...");

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnLogout)
                    .addComponent(lblWelcome))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tblArticles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Register Time", "Title", "Appoval", "Status", "Comment", "Last Edit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblArticles);

        btnAddArticle.setText("Add New Article");
        btnAddArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddArticleActionPerformed(evt);
            }
        });

        btnEditArticle.setText("Edit Article");
        btnEditArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditArticleActionPerformed(evt);
            }
        });

        btnDeleteArticle.setText("Delete Article");
        btnDeleteArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteArticleActionPerformed(evt);
            }
        });

        lblSearchArticle.setText("Search");

        txtSearchArticle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchArticleKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSearchArticle)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearchArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSearchArticle))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddArticle)
                        .addComponent(btnEditArticle)
                        .addComponent(btnDeleteArticle)))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginJFrame frmLogin = new LoginJFrame();
        frmLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtSearchArticleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchArticleKeyReleased
        // TODO add your handling code here:
        TableRowSorter<DefaultTableModel> rowSorter;
        rowSorter = new TableRowSorter<>((DefaultTableModel) tblArticles.getModel());
        tblArticles.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter(txtSearchArticle.getText()));
    }//GEN-LAST:event_txtSearchArticleKeyReleased

    private void btnAddArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddArticleActionPerformed
        // TODO add your handling code here:
        AddArticle frm = new AddArticle(this, journalist);
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddArticleActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        PapulateArticleTable();
    }//GEN-LAST:event_formWindowActivated

    private void btnDeleteArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteArticleActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblArticles.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblArticles.getModel();
        int id = (int) model.getValueAt(selectedRowIndex, 0);
        articles.Delete(id);

        JOptionPane.showMessageDialog(this, "Selected row deleted.");

        PapulateArticleTable();
    }//GEN-LAST:event_btnDeleteArticleActionPerformed

    private void btnEditArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditArticleActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblArticles.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to edit.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblArticles.getModel();
        int id = (int) model.getValueAt(selectedRowIndex, 0);
        EditArticle frm = new EditArticle(this, id);
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEditArticleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton btnAddArticle;
    private javax.swing.JButton btnDeleteArticle;
    private javax.swing.JButton btnEditArticle;
    private javax.swing.JButton btnLogout;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblSearchArticle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblArticles;
    private javax.swing.JTextField txtSearchArticle;
    // End of variables declaration//GEN-END:variables
}
