/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.Admin;

import business.dbAdmin;
import business.dbEditor;
import business.dbJournalist;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import ui.Main.LoginJFrame;

/**
 *
 * @author Azadeh
 */
public class AdminMain extends javax.swing.JFrame {

    private final dbAdmin admins;
    private final dbEditor editors;
    private final dbJournalist journalist;

    /**
     * Creates new form AdminMain
     */
    public AdminMain() {

        initComponents();

        admins = new dbAdmin();
        editors = new dbEditor();
        journalist = new dbJournalist();

        PapulateAdminTable();
        PapulateEditorTable();
        PapulateJournalistTable();
    }

    private void PapulateAdminTable() {

        DefaultTableModel model = (DefaultTableModel) tblAdmins.getModel();
        model.setRowCount(0);

        for (var item : admins.GetAdminList()) {

            Object[] row = new Object[7];
            row[0] = item.getId();
            row[1] = item.getFirstName();
            row[2] = item.getLastName();
            row[3] = item.getEmail();
            row[4] = item.getUsername();
            row[5] = item.getRecruitmentDate();
            row[6] = item.getSalary();

            model.addRow(row);
        }
    }

    private void PapulateEditorTable() {

        DefaultTableModel model = (DefaultTableModel) tblEditors.getModel();
        model.setRowCount(0);

        for (var item : editors.GetEditorList()) {

            Object[] row = new Object[7];
            row[0] = item.getId();
            row[1] = item.getFirstName();
            row[2] = item.getLastName();
            row[3] = item.getEmail();
            row[4] = item.getUsername();
            row[5] = item.getRecruitmentDate();
            row[6] = item.getSalary();

            model.addRow(row);
        }
    }

    private void PapulateJournalistTable() {

        DefaultTableModel model = (DefaultTableModel) tblJournalists.getModel();
        model.setRowCount(0);

        for (var item : journalist.GetJournalistList()) {

            Object[] row = new Object[7];
            row[0] = item.getId();
            row[1] = item.getFirstName();
            row[2] = item.getLastName();
            row[3] = item.getEmail();
            row[4] = item.getUsername();
            row[5] = item.getRecruitmentDate();
            row[6] = item.getSalary();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Admins = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdmins = new javax.swing.JTable();
        btnAddAdmin = new javax.swing.JButton();
        btnEditAdmin = new javax.swing.JButton();
        btnDeleteAdmin = new javax.swing.JButton();
        txtSearchAdmin = new javax.swing.JTextField();
        lblSearchAdmin = new javax.swing.JLabel();
        Editors = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEditors = new javax.swing.JTable();
        btnAddEditor = new javax.swing.JButton();
        btnEditEditor = new javax.swing.JButton();
        btnDeleteEditor = new javax.swing.JButton();
        lblSearchEditor = new javax.swing.JLabel();
        txtSearchEditor = new javax.swing.JTextField();
        Journalists = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblJournalists = new javax.swing.JTable();
        btnAddJournalist = new javax.swing.JButton();
        btnEditJournalist = new javax.swing.JButton();
        btnDeleteJournalist = new javax.swing.JButton();
        lblSearchJournalist = new javax.swing.JLabel();
        txtSearchJournalist = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Menu...");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TitlePanel.setBackground(new java.awt.Color(204, 0, 102));
        TitlePanel.setForeground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(0, 102, 102));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Administrators Main Menu...");

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnLogout))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tblAdmins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Firstname", "Lastname", "Email", "Username", "Register", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAdmins);

        btnAddAdmin.setText("Add New Admin");
        btnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminActionPerformed(evt);
            }
        });

        btnEditAdmin.setText("Edit Admin");
        btnEditAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAdminActionPerformed(evt);
            }
        });

        btnDeleteAdmin.setText("Delete Admin");
        btnDeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAdminActionPerformed(evt);
            }
        });

        txtSearchAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchAdminKeyReleased(evt);
            }
        });

        lblSearchAdmin.setText("Search");

        javax.swing.GroupLayout AdminsLayout = new javax.swing.GroupLayout(Admins);
        Admins.setLayout(AdminsLayout);
        AdminsLayout.setHorizontalGroup(
            AdminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(AdminsLayout.createSequentialGroup()
                        .addComponent(btnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(lblSearchAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        AdminsLayout.setVerticalGroup(
            AdminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AdminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAdmin)
                    .addComponent(btnEditAdmin)
                    .addComponent(btnDeleteAdmin)
                    .addComponent(txtSearchAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchAdmin))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Administrators", Admins);

        tblEditors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Firstname", "Lastname", "Email", "Username", "Register", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblEditors);

        btnAddEditor.setText("Add New Editor");
        btnAddEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEditorActionPerformed(evt);
            }
        });

        btnEditEditor.setText("Edit Editor");
        btnEditEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEditorActionPerformed(evt);
            }
        });

        btnDeleteEditor.setText("Delete Editor");
        btnDeleteEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEditorActionPerformed(evt);
            }
        });

        lblSearchEditor.setText("Search");

        txtSearchEditor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchEditorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout EditorsLayout = new javax.swing.GroupLayout(Editors);
        Editors.setLayout(EditorsLayout);
        EditorsLayout.setHorizontalGroup(
            EditorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditorsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                    .addGroup(EditorsLayout.createSequentialGroup()
                        .addComponent(btnAddEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSearchEditor)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        EditorsLayout.setVerticalGroup(
            EditorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditorsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EditorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEditor)
                    .addComponent(btnEditEditor)
                    .addComponent(btnDeleteEditor)
                    .addComponent(txtSearchEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchEditor))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Editor Chiefs", Editors);

        tblJournalists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Firstname", "Lastname", "Email", "Username", "Register", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblJournalists);

        btnAddJournalist.setText("Add New Journalist");
        btnAddJournalist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJournalistActionPerformed(evt);
            }
        });

        btnEditJournalist.setText("Edit Journalist");
        btnEditJournalist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditJournalistActionPerformed(evt);
            }
        });

        btnDeleteJournalist.setText("Delete Journalist");
        btnDeleteJournalist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteJournalistActionPerformed(evt);
            }
        });

        lblSearchJournalist.setText("Search");

        txtSearchJournalist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchJournalistKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JournalistsLayout = new javax.swing.GroupLayout(Journalists);
        Journalists.setLayout(JournalistsLayout);
        JournalistsLayout.setHorizontalGroup(
            JournalistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JournalistsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JournalistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                    .addGroup(JournalistsLayout.createSequentialGroup()
                        .addComponent(btnAddJournalist, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditJournalist, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteJournalist, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSearchJournalist)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchJournalist, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JournalistsLayout.setVerticalGroup(
            JournalistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JournalistsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JournalistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddJournalist)
                    .addComponent(btnEditJournalist)
                    .addComponent(btnDeleteJournalist)
                    .addComponent(txtSearchJournalist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchJournalist))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Journalists", Journalists);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchAdminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchAdminKeyReleased
        // TODO add your handling code here:
        TableRowSorter<DefaultTableModel> rowSorter;
        rowSorter = new TableRowSorter<>((DefaultTableModel) tblAdmins.getModel());
        tblAdmins.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter(txtSearchAdmin.getText()));
    }//GEN-LAST:event_txtSearchAdminKeyReleased

    private void txtSearchEditorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchEditorKeyReleased
        // TODO add your handling code here:
        TableRowSorter<DefaultTableModel> rowSorter;
        rowSorter = new TableRowSorter<>((DefaultTableModel) tblEditors.getModel());
        tblEditors.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter(txtSearchEditor.getText()));
    }//GEN-LAST:event_txtSearchEditorKeyReleased

    private void txtSearchJournalistKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchJournalistKeyReleased
        // TODO add your handling code here:
        TableRowSorter<DefaultTableModel> rowSorter;
        rowSorter = new TableRowSorter<>((DefaultTableModel) tblJournalists.getModel());
        tblJournalists.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter(txtSearchJournalist.getText()));
    }//GEN-LAST:event_txtSearchJournalistKeyReleased

    private void btnDeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAdminActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblAdmins.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblAdmins.getModel();
        int id = (int) model.getValueAt(selectedRowIndex, 0);
        admins.Delete(id);

        JOptionPane.showMessageDialog(this, "Selected row deleted.");

        PapulateAdminTable();
    }//GEN-LAST:event_btnDeleteAdminActionPerformed

    private void btnDeleteEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEditorActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEditors.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblEditors.getModel();
        int id = (int) model.getValueAt(selectedRowIndex, 0);
        editors.Delete(id);

        JOptionPane.showMessageDialog(this, "Selected row deleted.");

        PapulateEditorTable();
    }//GEN-LAST:event_btnDeleteEditorActionPerformed

    private void btnDeleteJournalistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteJournalistActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblJournalists.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblJournalists.getModel();
        int id = (int) model.getValueAt(selectedRowIndex, 0);
        journalist.Delete(id);

        JOptionPane.showMessageDialog(this, "Selected row deleted.");

        PapulateJournalistTable();
    }//GEN-LAST:event_btnDeleteJournalistActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginJFrame frmLogin = new LoginJFrame();
        frmLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
        // TODO add your handling code here:
        AddAdmin frm = new AddAdmin(this);
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        PapulateAdminTable();
        PapulateEditorTable();
        PapulateJournalistTable();
    }//GEN-LAST:event_formWindowActivated

    private void btnEditAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAdminActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblAdmins.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to edit.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblAdmins.getModel();
        int id = (int) model.getValueAt(selectedRowIndex, 0);
        EditAdmin frm = new EditAdmin(this, id);
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEditAdminActionPerformed

    private void btnAddEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEditorActionPerformed
        // TODO add your handling code here:
        AddEditor frm = new AddEditor(this);
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddEditorActionPerformed

    private void btnAddJournalistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJournalistActionPerformed
        // TODO add your handling code here:
        AddJournalist frm = new AddJournalist(this);
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddJournalistActionPerformed

    private void btnEditJournalistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditJournalistActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblJournalists.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to edit.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblJournalists.getModel();
        int id = (int) model.getValueAt(selectedRowIndex, 0);
        EditJournalist frm = new EditJournalist(this, id);
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEditJournalistActionPerformed

    private void btnEditEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEditorActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEditors.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to edit.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblEditors.getModel();
        int id = (int) model.getValueAt(selectedRowIndex, 0);
        EditEditor frm = new EditEditor(this, id);
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEditEditorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admins;
    private javax.swing.JPanel Editors;
    private javax.swing.JPanel Journalists;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnAddEditor;
    private javax.swing.JButton btnAddJournalist;
    private javax.swing.JButton btnDeleteAdmin;
    private javax.swing.JButton btnDeleteEditor;
    private javax.swing.JButton btnDeleteJournalist;
    private javax.swing.JButton btnEditAdmin;
    private javax.swing.JButton btnEditEditor;
    private javax.swing.JButton btnEditJournalist;
    private javax.swing.JButton btnLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblSearchAdmin;
    private javax.swing.JLabel lblSearchEditor;
    private javax.swing.JLabel lblSearchJournalist;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblAdmins;
    private javax.swing.JTable tblEditors;
    private javax.swing.JTable tblJournalists;
    private javax.swing.JTextField txtSearchAdmin;
    private javax.swing.JTextField txtSearchEditor;
    private javax.swing.JTextField txtSearchJournalist;
    // End of variables declaration//GEN-END:variables
}
